# Generated by Django 2.0.2 on 2018-03-28 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=500)),
                ('karma', models.SmallIntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_pic', models.ImageField(upload_to='../static/note_app/assets/profiles/')),
                ('karma', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['profile_id'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='note',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='karma',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='../static/note_app/assets/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Profile'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(upload_to='../static/note_app/assets/notes/'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='note_app.Note'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_history',
            field=models.ManyToManyField(blank=True, related_name='post_history', to='note_app.Comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded',
            field=models.ManyToManyField(blank=True, related_name='uploaded', to='note_app.Note'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Note'),
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='note_app.Comment'),
        ),
    ]
