# Generated by Django 2.0.2 on 2018-03-06 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['note_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_name']},
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=180, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.CharField(max_length=40, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='note',
            name='school',
            field=models.CharField(max_length=50, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(max_length=40, verbose_name='Semester'),
        ),
    ]
