# Generated by Django 2.0.2 on 2018-03-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_auto_20180328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(upload_to='../model_files/notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='../model_files/thumbnails/'),
        ),
    ]
