# Generated by Django 2.0.2 on 2018-03-29 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_auto_20180328_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_schedule',
            field=models.ManyToManyField(blank=True, related_name='course_schedule', to='note_app.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='fav_authors', to='note_app.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
