# Generated by Django 2.0.2 on 2018-03-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_auto_20180328_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_authors',
        ),
    ]
