# Generated by Django 2.0.2 on 2018-03-29 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0004_remove_profile_favorite_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course_schedule',
        ),
    ]
