# Generated by Django 2.0.2 on 2018-03-29 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0004_auto_20180328_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_schedule',
            field=models.ManyToManyField(blank=True, related_name='course_schedule', to='note_app.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='fav_authors', to='note_app.Profile'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(upload_to='../media/notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='../media/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='../media/profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
