# Generated by Django 2.0.2 on 2018-03-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0007_remove_profile_favorite_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course_schedule',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='_profile_favorite_authors_+', to='note_app.Profile'),
        ),
    ]
