# Generated by Django 2.0.2 on 2018-03-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0008_auto_20180328_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_schedule',
            field=models.ManyToManyField(blank=True, related_name='_profile_course_schedule_+', to='note_app.Profile'),
        ),
    ]
