# Generated by Django 2.0.4 on 2018-04-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0008_auto_20180415_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
