# Generated by Django 2.0.4 on 2018-04-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0009_remove_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='karma',
        ),
    ]
