# Generated by Django 2.0.2 on 2018-03-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0010_auto_20180328_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course_schedule',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_authors',
        ),
    ]
