# Generated by Django 2.0.2 on 2018-03-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0011_auto_20180328_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_schedule',
            field=models.ManyToManyField(blank=True, related_name='course_schedule', to='note_app.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='fav_authors', to='note_app.Profile'),
        ),
    ]
