# Generated by Django 2.0.4 on 2018-04-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0011_auto_20180418_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
    ]
