# Generated by Django 2.0.2 on 2018-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0013_auto_20180422_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='note_app.Note'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded',
            field=models.ManyToManyField(related_name='uploaded', to='note_app.Note'),
        ),
    ]
