# Generated by Django 2.0.2 on 2018-04-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0014_auto_20180422_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uploaded',
        ),
    ]
